openapi: 3.0.3
info:
  title: Expenses.API
  version: "1.0.0"
  description: API contract template for Expenses.API — fill in models and operations.
servers:
  - url: https://api.example.com/api/v1
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Expense:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date
        amount:
          type: number
          format: double
        currency:
          type: string
        category:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
      required: [date, amount, currency, category]
paths:
  /expenses:
    get:
      summary: List expenses
      tags: [Expenses]
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: perPage
          in: query
          schema:
            type: integer
            default: 25
      responses:
        "200":
          description: A paged list of expenses
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Expense"
                  meta:
                    type: object
      security:
        - BearerAuth: []
    post:
      summary: Create an expense
      tags: [Expenses]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Expense"
      responses:
        "201":
          description: Created
          headers:
            Location:
              schema:
                type: string
  /expenses/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get expense by id
      responses:
        "200":
          description: Expense found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Expense"
    put:
      summary: Update expense
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Expense"
      responses:
        "200":
          description: Updated
    delete:
      summary: Delete expense
      responses:
        "204":
          description: Deleted
security:
  - BearerAuth: []
tags:
  - name: Expenses
    description: Operations related to expenses
